version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building the project...
      - aws sts get-caller-identity
      - aws s3 ls s3://kadai5s3-2
      - aws deploy push --application-name kadai5app --s3-location s3://kadai5s3-2/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
